### ISSUE TITLE
Please update to last StructureMap and Caliburn.Micro

### ISSUE THREAD

**Issue by Ales999** [flq/Scal#1]
Hello !

If you have time, please update the project to the latest versions.
My qualifications do not have enough to do it myself.
Thank you in advance.

**Comment by flq** [comment]
Dear Ales,
I have last touched this code in 2012, and the last time I worked with WPF was in 2013. I am afraid that I do not have the time to do this.

**Comment by Ales999** [comment]
Ok, close issue
